### PR TITLE
Controller handles movement function

### PR DESCRIPTION
**Pull request by DexterWurnWSU**

### CODE REVIEW

**Comment by Bravo-0-29er** [comment]
Commits look good. handle_controller_movement looks almost identical to the keyboard handling so this is a good strategy to follow to maintain readability. The function for handling joystick movement has several lines of printf statements that are simply commented out after testing was done...I'm assuming. These commented tests could probably be removed.

**Review by Bravo-0-29er — COMMENTED** [review]
Commits look good. handle_controller_movement looks almost identical to the keyboard handling so this is a good strategy to follow to maintain readability. The function for handling joystick movement has several lines of printf statements that are simply commented out after testing was done...I'm assuming. These commented tests could probably be removed.

**Review by NathanDunkman — COMMENTED** [review]
Everything looks fine. Thanks for commenting out the printf statements

**Comment by BrodyEngle-Burdette** [comment]
The vector checking is very nicely implemented, and controller use will be so much better now. The printf's for checking are a nice edition if the user would like a graphical display of the button.

**Comment by rileymoore4521** [comment]
Looks good and has error handling. Clean implementation

**Pull request merged**
