### PR TITLE
Added more function with controller

### PR DESCRIPTION
**Pull request by DexterWurnWSU**
The major change here is being able to destroy and place blocks on controller as well as a few more simple additions. This is a minor change, but it took awhile because we are using an older version of GLFW which does not have event handling for controller inputs.

### CODE REVIEW

**Review by NathanDunkman — COMMENTED** [review]
This looks good. I'm guessing the reverted Easy Close and Zoom pull request was closed to add those functions into this one and further improve them?

**Comment by BrodyEngle-Burdette** [comment]
The newer versions of GLFW make this so much easier but good changes, especially with the older version. The controller support is very nice, also nice cleaning code up.

**Comment by DexterWurnWSU** [comment]
> This looks good. I'm guessing the reverted Easy Close and Zoom pull request was closed to add those functions into this one and further improve them?

Not sure about the revert, but this does implement all the keystrokes the keyboard can go to controller.

**Comment by DexterWurnWSU** [comment]
> The newer versions of GLFW make this so much easier but good changes, especially with the older version. The controller support is very nice, also nice cleaning code up.

Yes, I attempted to add the newer version however quickly realized that would be a project overhaul because of base drawing implementation from out of date functions.

**Comment by Bravo-0-29er** [comment]
> This looks good. I'm guessing the reverted Easy Close and Zoom pull request was closed to add those functions into this one and further improve them?

I've come to the conclusion that this is not the case. It would appear that this was an unintended side effect of a commit that went directly to the master branch. These functionalities will need to be re-added at some point in the future.

**Comment by towny802** [comment]
I've looked over this code, looks good to me.

**Comment by rileymoore4521** [comment]
Code looks good. GOod implementation and choice of function to make

**Pull request merged**
