### PR TITLE
1.1,1.2

### PR DESCRIPTION
**Pull request by rileymoore4521**
Added new textures for placeable blocks. Obsidian, gold, pumpkin, and diamond were added. Bulbasaur is in there for fun as it was a test block.

### CODE REVIEW

**Review by DexterWurnWSU — COMMENTED** [review]
mouse conflict is in this branch. I will correct the conflict. 5 textures added, should focus on natural block before adding others.

**Comment by DexterWurnWSU** [comment]
fixed the conflict

**Comment by towny802** [comment]
This code functions to spec, and follows the code conventions of existing block types.

**Review by NathanDunkman — COMMENTED** [review]
Looks good. Are there any other blocks you're looking to add?

**Review by BrodyEngle-Burdette — COMMENTED** [review]
This is a nice and clean way of getting the id of the block for the /block command. The bounds of the if statement will have to be manually changed if more and more blocks are added.

**Pull request merged**
