### PR TITLE
Tasks 14 and 19

### PR DESCRIPTION
**Pull request by Bravo-0-29er**
Pull Request to add functionality defined by User Stories 14 and 19: Addition of an in game clock and local time. Ability to hide status text with keypress.

### CODE REVIEW

**Comment by DexterWurnWSU** [comment]
Everything looks good. I am going to move the functionality into on_key_press and out of handle movement. To better keep everything organized. In game time is pretty cool honestly.

**Review by DexterWurnWSU — APPROVED** [review]
I moved the functionality into on key press and it works well

**Review by NathanDunkman — COMMENTED** [review]
Did you ever fix the flickering issue? you may need to slow down how fast it updates

**Review by BrodyEngle-Burdette — COMMENTED** [review]
Nice keeping it consistent, and cleaning up the code. The top left corner is a very visually appealing place for the game time

**Comment by DexterWurnWSU** [comment]
> Did you ever fix the flickering issue? you may need to slow down how fast it updates

I have not found a solution for this yet. I am thinking about having a method to get last time something was pressed and wait at least a second before allowing it again.

**Comment by rileymoore4521** [comment]
Good feature implementation and has a key bound to it now making it a very nice quality of life feature.

**Pull request merged**
