### PR TITLE
Completion of Tasks 20.1 / 20.2

### PR DESCRIPTION
**Pull request by Bravo-0-29er**
Added hideable help menu that displays default controls

### CODE REVIEW

**Review by DexterWurnWSU — COMMENTED** [review]
This is a good piece to add. May consider even creating a help command to give instead of displaying normally.

**Review by DexterWurnWSU — COMMENTED** [review]
You may want to add this to the read me that shows all key binds, so that the project is more complete. I appreciate you adding the new stuff to the "on key" instead "on movement" as previously done.

**Comment by DexterWurnWSU** [comment]
This looks good. I will change the F1 key to be stated with functionality on the read me. I originally thought the reviews would be by commit rather than by pull request apologizes.

**Comment by BrodyEngle-Burdette** [comment]
Good code cleanup and optimizations, I like the small touches for checking hide clock in stead of comparing it to zero. A Help menu is definitely a useful piece to add, I agree with a command statement though might be easier to use.

**Comment by rileymoore4521** [comment]
Good variable names and has a straightforward implementation that's easy to follow. Looks good to me

**Pull request merged**
