### PR TITLE
Easier to close game for players and zoom is easier to access, and reduced mouse speed

### PR DESCRIPTION
**Pull request by DexterWurnWSU**
how it look?

### CODE REVIEW

**Comment by towny802** [comment]
This looks good, the feature works, and is integrated into existing code

**Review by NathanDunkman — COMMENTED** [review]
Does this not work with controller? only keyboard?

**Review by BrodyEngle-Burdette — COMMENTED** [review]
The mouse speed was very fast at some points, these changes are much needed. All added code is consistent with the source.

**Comment by rileymoore4521** [comment]
The mouse change was definitely a good one. This game has quite a few shortcomings with mouse movement so this was a step in the right direction of rectifying it. The code implementation is short so it's easy to see what's changed and DEF names are clear. Good job.

**Pull request closed without merging**
