### PR TITLE
Easy close and zoom

### PR DESCRIPTION
**Pull request by DexterWurnWSU**

### CODE REVIEW

**Comment by towny802** [comment]
This works, and the code is minimal, and built into the existing control loops

**Review by NathanDunkman — COMMENTED** [review]
Did this change the necessary buttons to close the game?

**Review by BrodyEngle-Burdette — COMMENTED** [review]
The fov change is really nice for this effect, I like it a bit further zoomed in, maybe to around 100.

**Comment by rileymoore4521** [comment]
I tested this in game and have to agree with brodys review that it could probably be a bit closer. I can't really tell what im looking at but cool feature nonetheless

**Pull request merged**
