### PR TITLE
Finalized controller

### PR DESCRIPTION
**Pull request by DexterWurnWSU**
This is testable with an Xbox One controller.

### CODE REVIEW

**Comment by BrodyEngle-Burdette** [comment]
These checks make the controller a lot more smooth, and good cleanup. May need to delete old comments for testing purposes

**Comment by DexterWurnWSU** [comment]
merge conflicts are now resolved

**Comment by rileymoore4521** [comment]
Code looks clean. The variable names could have been better but that was a design choice of the original writer.

**Comment by rileymoore4521** [comment]
I see it's currently set up for the Xbox controller are any other controllers able to be supported like PlayStation or even maybe a joystick? Would be cool to have multiple options!

**Pull request merged**
