### PR TITLE
16.4

### PR DESCRIPTION
**Pull request by rileymoore4521**
Added command for block selection from placeable array

### CODE REVIEW

**Review by DexterWurnWSU — COMMENTED** [review]
I tried breaking your code but instead... it broke me. Good error checking.

**Comment by towny802** [comment]
This code functions to spec, and did not change the coding convention already in use.

**Review by NathanDunkman — COMMENTED** [review]
if the blocknum get subtracted by 1 after being checked if its greater than 0, why not just check if blocknum >= 0?

**Review by BrodyEngle-Burdette — COMMENTED** [review]
Nice using the same sscanf to keep it consistent, and to the set standard. The code errors checks and and is implemented good.

**Pull request merged**
