### PR TITLE
Revert "Easy close and zoom"

### PR DESCRIPTION
**Pull request by towny802**
Reverts towny802/Craft#2

We need to do a review of this

### CODE REVIEW

**Review by NathanDunkman — COMMENTED** [review]
what was the point of reverting this? did it conflict with another change?

**Review by BrodyEngle-Burdette — COMMENTED** [review]
The zoom was buggy and slowed down the game, it is probably not rendering the change in perspective fast enough..

**Comment by DexterWurnWSU** [comment]
Zoom implementation was the same as it originally was. Only changed that happened to zoom was a key change.

**Comment by rileymoore4521** [comment]
Looks like something got pushed over and then reverted? And yeah only the key changed. Everything else is the same. Hopefully nothing else got messed up >.>

**Pull request closed without merging**
